version: "1.0.0"
env: "local" 
storage: 
  migrationfile:  "file://migrations/postgres"
  driver:   "postgres"
  user:     "yerda"
  password: "password:"
  host:     "db"
  port:     5432
  dbname:   "dbauth"
  sslmode: "disable"
http:
  address: ":8080"
  timeout: "5s"
  idle: "15s"
jwt:
  secret: "reallyahardsecret"
  expiration: "5m"
otp:
  length: 4
  expiration: "3m"
