version: '3.9'

services:
  web:
      build: .
      env_file:
        - .env
      ports:
        - 8080:8080
      volumes:
        - .:/usr/src/app
      command: go run main.go -config=config.yaml

      depends_on:
        - db
  db:
      image:  postgres:latest
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      ports:
        - 5432:5432
  migrate:
    image: migrate/migrate:latest
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [ "migrate",
      "-path",
      "/migrations",
      "/-database",
      "postgres://yerda:password@db:5432/authdb?sslmode=disable",
     ]
    command: ["up"]
    depends_on:
      - db