version: '3.9'

services:
  web:
      build: .
      env_file:
        - .env  
      ports:
        - 8080:8080
      volumes:
        - .:/usr/src/app
      command: go run main.go -config=config.yaml

      depends_on:
        - db
  db:
      image:  postgres:latest
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      ports:
        - 1234:5432